### ISSUE TITLE
Configurable windowsUnityPath

### ISSUE THREAD

**Issue by bfowle** [mindcandy/Teamcity-unity3d-build-runner-plugin#13]
Hello--

The windowsUnityPath is currently hardcoded to the 32bit "Program Files (x86)" path, however on the new 5.0+ Unity, there is a possibility this will be installed in the 64bit "Program Files" folder instead.

It would be nice if this could be overridden and/or detected instead.

Cheers~

**Comment by mcmarkb** [comment]
Rolling a fix for this into #7 by searching both 32/64 bit paths.

**Comment by markltbaker** [comment]
New version now searches both paths for installed Unity editors so hopefully fixes this!
