### ISSUE TITLE
New Prebuilt Runner Zip?

### ISSUE THREAD

**Issue by MikeMcShaffry** [mindcandy/Teamcity-unity3d-build-runner-plugin#15]
Hello - I've attempted to build the latest Unity Runner via IDEA under Windows, but for some reason the runner type doesn't show up when creating new build configurations. I didn't have any errors in the build, and the plugin shows up in the TeamCity configured plugins list....

Anyway, I was hoping you could create a new prebuilt runner ZIP file for me? The one currently linked on the project home page is from 2013. 

Many thanks!
Mike.

**Comment by IainGilfeather** [comment]
Hello. A latest prebuilt runner would be super useful for us too. If anyone has one they can share that would be great. If not, I may have managed to build one myself by the end of this week and I'll share it.

(Thanks for sharing Unity Runner, Mark)

Cheers,
Iain

**Comment by Soft-Shock** [comment]
See egorulshin's solution in Issue 16

>Try to check the teamcity log on the server. Maybe some errors occur during plugin starting.
>
>I had the same issue. It was related to version of java on the server. I built the plugin with using JDK1.8, but there is JDK 1.7 on the server. I've got UnsupportedClassVersionError exception which were logged in teamcity-server.log. I rebuilt the plugin with JDK1.6 and reinstalled it. After this it started work without any errors and the plugin appeared in the build steps.

**Comment by markltbaker** [comment]
have a new prebuilt version but currently for JDK1.8 - please let me know if older versions are needed.

**Comment by m-metz** [comment]
Thanks Mark!
