### ISSUE TITLE
Build Agent: Windows 10 mistaken as Mac, Unity not found

### ISSUE THREAD

**Issue by huwb** [mindcandy/Teamcity-unity3d-build-runner-plugin#31]
Hello,

We installed a build agent on a Win10 box and connected it to a TC9.1 server. It reports requirements being unmet, with the message "Exception getting finding unity versions". Looking at the source, we think it is misidentifying the system as a Mac box and using /Applications as the path to look for unity. As a test we copied the Unity folder from Program Files to c:\Applications and the runner successfully found it and was happy, which seems to indicate that it is in fact doing a search and is able to find Unity, but is looking in the wrong place.

**Comment by ArtOfSettling** [comment]
Bit late, but try the following slight modification : 

https://github.com/ArtOfSettling/Teamcity-unity3d-build-runner-plugin/commit/5046c866e8f783fcf282e4aaaa4a9970a9de7650

**Comment by huwb** [comment]
Apologies I have just discovered this reply!! I'm not using this build runner since some time so I'll just close this. Thanks for the reply though!
