### ISSUE TITLE
Build Path issues in Windows

### ISSUE THREAD

**Issue by bfowle** [mindcandy/Teamcity-unity3d-build-runner-plugin#5]
Hello--
First off, great plugin! Well done.
I have been noticing some issues with setting the Build Path in Windows:
(I have the clearBefore and cleanAfter flags both checked.)

1.) Setting the path with *.exe at the end: (e.g. c:\repo\builds\game.exe) - the first time this runs, it works correctly. Creates the game.exe, folder tree is also correct. The second time it runs, however, it errors:

[Step 1/1] Removing output directory: c:\repo\builds\game.exe
[Step 1/1] java.lang.IllegalArgumentException: c:\repo\builds\game.exe is not a directory

2.) Setting the path without the *.exe at the end (e.g. c:\repos\builds\), builds the data directories but upon moving the default exe created errors with:

[Step 1/1] Error building Player: IOException: Failed to Move File / Directory from 'Temp/StagingArea/player_win.exe' to 'c:/repo/builds/'.

**Comment by mcmarkb** [comment]
looking at fixing this along with #7

**Comment by markltbaker** [comment]
Whilst updating the plugin to fix other issues, I added some .isDirectory() guards around the deleteDirectory() call so that should resolve it.
