### ISSUE TITLE
Support multiple versions of unity installed on a single build agent

### ISSUE THREAD

**Issue by mcmarkb** [mindcandy/Teamcity-unity3d-build-runner-plugin#7]
As we have multiple teams using Unity3d and sharing the build machines, we should allow multiple versions installed at the same time.
Unity has an installer BUT you can rename/move the folder after install.
So we could require all Unity versions to be installed in /Applications/UnityVersions/...
We can then auto detect the actual version from the info.plist file
To specify which version, we can use Agent Requirements and/or a new version parameter on the Unity Runner. This would select a MAJOR and MINOR version number.
The Build Runner can add any number of version parameters as Agent Parameters in the format unity.version.MAJOR.MINOR e.g. unity.version.4.3=4.3.2f4
unity.version.5.1=5.1.0beta4

(MC story TOOL-606)

**Comment by mcmarkb** [comment]
Update: working on this now. If anyone is using Windows/Mac and wants to test it out please let me know!

**Comment by markltbaker** [comment]
Seems to be working here so closing, but please do give me feedback as I'm happy to fix bugs where they are found :)
